CREATE TABLE accounts(
  id VARCHAR(255) NOT NULL primary key COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  name VARCHAR(255) NOT NULL COMMENT 'users given name',
  email VARCHAR(255) NOT NULL COMMENT 'auth email',
  picture VARCHAR(255) NOT NULL COMMENT 'picture url'
) DEFAULT CHARSET utf8 COMMENT '';
CREATE TABLE jobs(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  name VARCHAR(255) NOT NULL COMMENT 'job name',
  creatorId VARCHAR(255) NOT NULL COMMENT 'FK: user account',
  description VARCHAR(255) NOT NULL COMMENT 'description',
  FOREIGN KEY (creatorId) REFERENCES accounts(id) ON DELETE CASCADE
) DEFAULT CHARSET utf8 COMMENT '';
CREATE TABLE contractors(
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY COMMENT 'primary key',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT 'create time',
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'update time',
  name VARCHAR(255) NOT NULL COMMENT 'contractor name',
  accountId varchar(255) NOT NULL COMMENT 'FK: user account',
  jobId INT NOT NULL COMMENT 'FK: job',
  FOREIGN KEY (accountId) REFERENCES accounts(id) ON DELETE CASCADE,
  FOREIGN KEY (jobId) REFERENCES jobs(id) ON DELETE CASCADE
) DEFAULT CHARSET utf8 COMMENT '';